name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Angular-Hello-World
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli


      - name: Build Angular app for GitHub Pages
        run: npm run build --prod
        working-directory : Angular-Hello-World

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: Angular-Hello-World/dist/Angular-Hello-World/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy 
        id: deployment
        uses: actions/deploy-pages@v4
